name: MacOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: run tests
      run: |
        cmake -Htest -Bbuild/test
        cmake --build build/test --target test-verbose
