name: Test MacOS

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    
    - name: run tests
      run: |
        cmake -Htest -Bbuild/test
        CTEST_OUTPUT_ON_FAILURE=1 cmake --build build/test --target test

    - name: build examples
      run: python3 examples/build_all.py
