name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    
    - name: run tests
      run: |
        cmake -Htest -Bbuild/test
        cmake --build build/test --target test-verbose
